"""Guardian benchmarks on the demo pipeline, at several scales.

    uv sync --extra observability                  # for configuration (d) below
    uv run python bench/run_bench.py               # 10k, 100k and 1M rows, 5 repeats
    uv run python bench/run_bench.py --scales 10000 100000
    uv run python bench/run_bench.py --quick       # 10k rows, 2 repeats: a sanity check
    uv run python bench/update_readme.py           # README Results table <- results.json

Measurements, each at every scale (rows generated by the source block):

1. Overhead breakdown: one pipeline run of the same blocks, on clean data,
   (a) bare: the block functions in topological order, no Guardian;
   (b) Guardian core only: validation, snapshots, quarantine, events at sample rate 0.1,
       with provenance recording switched off (a no-op provenance store);
   (c) (b) + provenance;
   (d) (c) + observability exporters: OpenLineage to a JSON-lines file and OpenTelemetry
       spans to an in-memory exporter.
   Each configuration's added cost is reported as a percentage over (a).
2. Throughput during an outage: rows/s for a clean run vs. a run in which a
   fallback-protected block crashes (its consumer reroutes to the fallback source) and
   vs. one in which an unprotected block crashes (its dependents read its stale
   last-good snapshot). Each timed run follows an untimed clean run in the same root.
3. Recovery time: wall time of `guardian shadow promote <block> --approve` (a separate
   process, as a human would run it) until it returns with the block HEALTHY, the
   candidate active and the quarantine replayed through it, with 1%, 10% and 50% of the
   block's rows quarantined.
4. Shadow cost: one pipeline run with one block's candidate version in shadow vs. none.

Blocks are chosen by DAG role (``blocks_by_role``), never by name. Methodology (warm-up,
repeats, fresh storage roots, statistics) is written into results.md.
"""

from __future__ import annotations

import argparse
import contextlib
import copy
import gc
import json
import os
import platform
import re
import shutil
import statistics
import subprocess
import sys
import tempfile
import time
from collections.abc import Callable, Iterator
from dataclasses import dataclass, field
from datetime import UTC, datetime
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path
from typing import Any

import pandas as pd
import yaml

from guardian.agent.eval import git_commit
from guardian.core.dag import blocks_by_role, dependents
from guardian.core.events import EventKind
from guardian.core.guardian import Guardian
from guardian.core.models import BlockStatus, PipelineSpec, QuarantineStatus
from guardian.core.provenance import LIVE
from guardian.core.refs import load_ref
from guardian.demo.faults import apply_faults, corrupt_rows, crash
from guardian.runner.executor import Executor, Outcome, RunReport
from guardian.runner.spec_loader import parse_spec, topological_order

BENCH = Path(__file__).resolve().parent
REPO = BENCH.parent
DEMO_SPEC = REPO / "guardian" / "demo" / "pipeline.yaml"

SCALES = (10_000, 100_000, 1_000_000)
REPEATS = 5
QUICK_SCALES = (10_000,)
QUICK_REPEATS = 2
SAMPLE_RATE = 0.1
QUARANTINE_FRACTIONS = (0.01, 0.10, 0.50)
MEASUREMENTS = ("overhead", "throughput", "recovery", "shadow")

OVERHEAD_CONFIGS = {
    "bare": "(a) bare functions, no Guardian",
    "core": "(b) Guardian core only (sample rate 0.1)",
    "provenance": "(c) + provenance",
    "observability": "(d) + observability exporters",
}
THROUGHPUT_CONFIGS = {
    "clean": "Clean run",
    "protected_crash": "Fallback-protected block crashed",
    "unprotected_crash": "Unprotected block crashed",
}
SHADOW_CONFIGS = {"none": "No block in shadow", "one": "One block in shadow"}


# ---------------------------------------------------------------- blocks and specs


@dataclass(frozen=True)
class Blocks:
    """The blocks each measurement uses, chosen by DAG role."""

    sources: tuple[str, ...]
    protected: str  # fallback_protected: crashed in the outage run
    consumer: str  # its dependent with the fallback edge
    fallback_source: str
    unprotected: str  # unprotected, not a source: its dependents read it stale
    versioned: str  # fallback_protected with a candidate version: recovery and shadow
    candidate: str  # that block's first non-active version

    def as_dict(self) -> dict[str, str | list[str]]:
        return {
            "source": list(self.sources),
            "fallback_protected (crashed)": self.protected,
            "its fallback consumer": self.consumer,
            "fallback_source": self.fallback_source,
            "unprotected (crashed)": self.unprotected,
            "shadow / recovery block": self.versioned,
            "candidate version": self.candidate,
        }


def raw_spec() -> dict[str, Any]:
    return yaml.safe_load(DEMO_SPEC.read_text(encoding="utf-8"))


def pick_blocks(spec: PipelineSpec) -> Blocks:
    roles = blocks_by_role(spec)
    protected = roles["fallback_protected"][0]
    consumer = next(b for b in dependents(spec, protected) if spec.block(b).fallback_for(protected))
    edge = spec.block(consumer).fallback_for(protected)
    assert edge is not None
    unprotected = next(b for b in roles["unprotected"] if b not in roles["source"])
    versioned = next(
        b
        for b in roles["fallback_protected"] + roles["unprotected"]
        if len(spec.block(b).versions) > 1 and spec.block(b).merge_key
    )
    block = spec.block(versioned)
    candidate = next(v for v in block.versions if v != block.active)
    return Blocks(
        tuple(roles["source"]), protected, consumer, edge.source, unprotected, versioned, candidate
    )


def scaled(
    raw: dict[str, Any],
    rows: int,
    *,
    clean: bool = False,
    thresholds: dict[str, float] | None = None,
) -> dict[str, Any]:
    """The raw demo spec with every source generating ``rows`` rows (``clean``: no
    injected data errors) and optional per-block quarantine thresholds."""
    raw = copy.deepcopy(raw)
    for block in raw["blocks"]:
        params = block.get("params") or {}
        if not block.get("inputs") and "rows" in params:
            params["rows"] = rows
            if clean:
                params["error_rate"] = 0.0
        if thresholds and block["name"] in thresholds:
            block["quarantine_threshold"] = thresholds[block["name"]]
    return raw


def to_spec(raw: dict[str, Any]) -> PipelineSpec:
    return parse_spec(raw, source=str(DEMO_SPEC))


def derived_columns(spec: PipelineSpec, block: str) -> list[str]:
    """Output columns ``block`` derives itself (not present in any of its inputs), from a
    small bare run: corrupting only those lets a fixed version re-derive them on replay."""
    outputs = bare_run(spec)
    seen = {c for u in spec.block(block).inputs for c in outputs[u].columns}
    return [c for c in outputs[block].columns if c not in seen] or list(outputs[block].columns)


# ---------------------------------------------------------------- run helpers


class NullProvenanceStore:
    """A provenance store that records nothing: Guardian with provenance switched off."""

    def record(self, provenance: Any) -> None:
        pass

    def get(self, block: str, run_id: str, store: str = LIVE) -> None:
        return None

    def records(self, store: str = LIVE) -> list[Any]:
        return []

    def record_run(self, run: Any) -> None:
        pass

    def runs(self, block: str | None = None) -> list[Any]:
        return []

    def session(self) -> contextlib.AbstractContextManager[None]:
        return contextlib.nullcontext()


def bare_run(spec: PipelineSpec) -> dict[str, pd.DataFrame]:
    """The same block functions in topological order, with no Guardian at all."""
    outputs: dict[str, pd.DataFrame] = {}
    for name in topological_order(spec):
        block = spec.block(name)
        fn = load_ref(block.fn)
        if block.load is not None:  # a source block's loader takes the params
            outputs[name] = fn(load_ref(block.load)(**block.params))
        else:
            outputs[name] = fn(*[outputs[u] for u in block.inputs], **block.params)
    return outputs


@contextlib.contextmanager
def fresh_root() -> Iterator[Path]:
    with tempfile.TemporaryDirectory(prefix="guardian-bench-", ignore_cleanup_errors=True) as d:
        yield Path(d)


def run(g: Guardian, run_id: str) -> RunReport:
    return Executor(g).run(run_id)


def timed(fn: Callable[[], Any]) -> tuple[float, Any]:
    start = time.perf_counter()
    result = fn()
    return time.perf_counter() - start, result


def cli_env() -> dict[str, str]:
    """The environment for CLI subprocesses, with any exporter configuration removed."""
    env = {
        k: v
        for k, v in os.environ.items()
        if not k.startswith(("GUARDIAN_OPENLINEAGE", "GUARDIAN_OTEL"))
    }
    return {**env, "COLUMNS": "200"}  # rich wraps output at 80 columns without a terminal


def log(msg: str) -> None:
    print(f"[{datetime.now():%H:%M:%S}] {msg}", flush=True)


# ---------------------------------------------------------------- statistics


@dataclass
class Series:
    measurement: str
    scale: int
    config: str
    label: str
    unit: str
    samples: list[float] = field(default_factory=list)
    notes: dict[str, Any] = field(default_factory=dict)
    skipped: str | None = None

    def summary(self) -> dict[str, Any]:
        out: dict[str, Any] = {
            "measurement": self.measurement,
            "scale": self.scale,
            "config": self.config,
            "label": self.label,
            "unit": self.unit,
            "samples": self.samples,
            "notes": self.notes,
        }
        if self.skipped:
            return {**out, "skipped": self.skipped}
        q1, med, q3 = quartiles(self.samples)
        return {**out, "median": med, "q1": q1, "q3": q3, "iqr": q3 - q1}


def quartiles(samples: list[float]) -> tuple[float, float, float]:
    """Q1, median, Q3 (inclusive method: with 5 samples, the 2nd and 4th values)."""
    if len(samples) == 1:
        return samples[0], samples[0], samples[0]
    q1, med, q3 = statistics.quantiles(samples, n=4, method="inclusive")
    return q1, med, q3


def measure(
    configs: list[tuple[Series, Callable[[], float]]], repeats: int, what: str
) -> list[Series]:
    """One untimed warm-up per configuration, then ``repeats`` measured repeats. The
    configurations are interleaved within each repeat, in an order rotated per repeat, so
    slow drift of the machine affects them all alike. Every call uses a fresh root."""
    for series, fn in configs:
        gc.collect()
        fn()
        log(f"  {what}: warm-up {series.config}")
    for rep in range(repeats):
        k = rep % len(configs)
        for series, fn in configs[k:] + configs[:k]:
            gc.collect()
            series.samples.append(fn())
        log(f"  {what}: repeat {rep + 1}/{repeats}")
    return [series for series, _ in configs]


# ---------------------------------------------------------------- 1. overhead


def bench_overhead(raw: dict[str, Any], scale: int, repeats: int) -> list[Series]:
    spec = to_spec(scaled(raw, scale, clean=True))  # bare blocks cannot survive bad rows
    series = {k: Series("overhead", scale, k, v, "s") for k, v in OVERHEAD_CONFIGS.items()}

    def bare() -> float:
        seconds, outputs = timed(lambda: bare_run(spec))
        series["bare"].notes["rows_out"] = {b: len(df) for b, df in outputs.items()}
        return seconds

    def guardian(config: str) -> Callable[[], float]:
        def go() -> float:
            with fresh_root() as root:
                provenance = NullProvenanceStore() if config == "core" else None
                with Guardian(spec, root, sample_rate=SAMPLE_RATE, provenance=provenance) as g:
                    spans = attach_exporters(g, root) if config == "observability" else None
                    seconds, report = timed(lambda: run(g, "r1"))
                    assert report.ok, [(r.block, r.outcome, r.reason) for r in report.blocks]
                    assert not g.events.query(kind=EventKind.ERROR)
                    s = series[config]
                    s.notes["events_emitted"] = len(g.events.query()) + g.events.sampled_out
                    if spans is not None:
                        s.notes["spans_exported"] = len(spans.get_finished_spans())
                        lineage = (root / "openlineage.jsonl").read_text(encoding="utf-8")
                        s.notes["openlineage_events"] = len(lineage.splitlines())
            return seconds

        return go

    configs: list[tuple[Series, Callable[[], float]]] = [(series["bare"], bare)]
    configs += [(series[c], guardian(c)) for c in ("core", "provenance")]
    missing = observability_missing()
    if missing:
        series["observability"].skipped = missing
    else:
        configs.append((series["observability"], guardian("observability")))
    measure(configs, repeats, f"overhead {scale:,}")
    return list(series.values())


def observability_missing() -> str | None:
    try:
        import opentelemetry.sdk  # noqa: F401
    except ImportError:
        return "OpenTelemetry not installed (uv sync --extra observability)"
    return None


def attach_exporters(g: Guardian, root: Path) -> Any:
    from opentelemetry.sdk.trace import TracerProvider
    from opentelemetry.sdk.trace.export import SimpleSpanProcessor
    from opentelemetry.sdk.trace.export.in_memory_span_exporter import InMemorySpanExporter

    from guardian.observability.openlineage import FileTransport, OpenLineageEmitter
    from guardian.observability.otel import SpanEmitter

    exporter = InMemorySpanExporter()
    provider = TracerProvider()
    provider.add_span_processor(SimpleSpanProcessor(exporter))
    g.events.add_listener(
        OpenLineageEmitter(g.spec.name, FileTransport(root / "openlineage.jsonl"))
    )
    g.events.add_listener(SpanEmitter(provider.get_tracer("guardian-bench"), g.spec.name))
    return exporter


# ---------------------------------------------------------------- 2. throughput


def bench_throughput(raw: dict[str, Any], scale: int, repeats: int, blocks: Blocks) -> list[Series]:
    spec = to_spec(scaled(raw, scale))  # the demo's messy data, as a real run sees it
    series = {k: Series("throughput", scale, k, v, "rows/s") for k, v in THROUGHPUT_CONFIGS.items()}
    faulted = {
        "clean": (spec, {}),
        "protected_crash": apply_faults(spec, {blocks.protected: [crash("bench outage")]}),
        "unprotected_crash": apply_faults(spec, {blocks.unprotected: [crash("bench outage")]}),
    }

    def go(config: str) -> Callable[[], float]:
        def timed_run() -> float:
            s, registry = faulted[config]
            with fresh_root() as root:
                with Guardian(spec, root, sample_rate=SAMPLE_RATE) as g:  # untimed clean r0
                    assert run(g, "r0").ok
                with Guardian(s, root, sample_rate=SAMPLE_RATE, registry=registry) as g:
                    seconds, report = timed(lambda: run(g, "r1"))
                check_outage(config, report, blocks)
                series[config].notes["rows_promoted_per_leaf"] = {
                    r.block: r.rows_out  # rows_out counts promoted rows only
                    for r in report.blocks
                    if not dependents(spec, r.block)
                }
            return scale / seconds

        return timed_run

    measure([(series[c], go(c)) for c in series], repeats, f"throughput {scale:,}")
    return list(series.values())


def check_outage(config: str, report: RunReport, blocks: Blocks) -> None:
    if config == "clean":
        assert report.ok, [(r.block, r.outcome, r.reason) for r in report.blocks]
        return
    crashed = blocks.protected if config == "protected_crash" else blocks.unprotected
    r = report.get(crashed)
    assert (r.outcome, r.reason) == (Outcome.ROLLBACK, "crash"), (r.outcome, r.reason)
    if config == "protected_crash":
        consumer = report.get(blocks.consumer)
        assert consumer.outcome is Outcome.PASS and consumer.rerouted
        assert blocks.fallback_source in {ref.block for ref in consumer.sources}
    else:
        for d in dependents_of(report, crashed):
            assert d.outcome is Outcome.PASS and d.stale, (d.block, d.outcome, d.sources)


def dependents_of(report: RunReport, block: str) -> list[Any]:
    return [r for r in report.blocks if any(ref.requested == block for ref in r.sources)]


# ---------------------------------------------------------------- 3. recovery


PROMOTED = re.compile(
    r"replayed\s+(\d+)\s+quarantined\s+record\(s\).*?still\s+failing\s+(\d+)", re.S
)


def bench_recovery(
    raw: dict[str, Any], scale: int, repeats: int, blocks: Blocks, columns: list[str]
) -> list[Series]:
    block, candidate = blocks.versioned, blocks.candidate
    threshold = to_spec(raw).block(block).quarantine_threshold
    series: dict[str, Series] = {}
    configs: list[tuple[Series, Callable[[], float]]] = []
    floor = Series("recovery", scale, "cli_floor", "`guardian status` (CLI start-up floor)", "s")

    for fraction in QUARANTINE_FRACTIONS:
        # The live version's bad deploy garbles ``fraction`` of the block's rows. The
        # threshold is raised just above it so exactly those rows are quarantined and
        # the rest promoted (at the demo's threshold a large fraction would roll back
        # and quarantine every row).
        thresholds = {block: max(threshold, round(fraction + 0.05, 4))}
        raw_f = scaled(raw, scale, clean=True, thresholds=thresholds)
        spec = to_spec(raw_f)
        bad = apply_faults(spec, {block: [corrupt_rows(fraction, columns, seed=7, unique=True)]})
        config = f"{fraction:.0%}"
        s = Series("recovery", scale, config, f"{fraction:.0%} of rows quarantined", "s")
        series[config] = s

        def go(raw_f=raw_f, spec=spec, bad=bad, s=s, fraction=fraction) -> float:
            with fresh_root() as root:
                spec_path = root / "pipeline.yaml"
                spec_path.write_text(yaml.safe_dump(raw_f, sort_keys=False), encoding="utf-8")
                # Untimed setup: clean r0; r1 with the bad deploy; the block taken OUT;
                # the fixed version in shadow for one run.
                with Guardian(spec, root, sample_rate=SAMPLE_RATE) as g:
                    assert run(g, "r0").ok
                with Guardian(bad[0], root, sample_rate=SAMPLE_RATE, registry=bad[1]) as g:
                    r1 = run(g, "r1").get(block)
                    assert r1.outcome is Outcome.PASS, (r1.outcome, r1.reason)
                with Guardian(spec, root, sample_rate=SAMPLE_RATE) as g:
                    g.set_block_status(block, BlockStatus.OUT)
                    g.shadow_start(block, candidate)
                    run(g, "s1")
                    held = g.quarantine.count(block, QuarantineStatus.QUARANTINED)
                assert held == r1.quarantined > 0
                cli = [sys.executable, "-m", "guardian.runner.cli"]
                where = ["--spec", str(spec_path), "--root", str(root)]
                status_s, done = timed(
                    lambda: subprocess.run(
                        [*cli, "status", *where], capture_output=True, text=True, env=cli_env()
                    )
                )
                assert done.returncode == 0, done.stderr[-2000:]
                floor.samples.append(status_s)
                # Timed: the promotion, as a human would run it.
                seconds, done = timed(
                    lambda: subprocess.run(
                        [*cli, "shadow", "promote", block, "--approve", *where],
                        capture_output=True,
                        text=True,
                        env=cli_env(),
                    )
                )
                assert done.returncode == 0, done.stdout[-2000:] + done.stderr[-2000:]
                match = PROMOTED.search(done.stdout)
                assert match, done.stdout
                replayed, still_failing = int(match[1]), int(match[2])
                with Guardian(spec, root) as g:
                    assert g.status(block) is BlockStatus.HEALTHY
                    assert g.active_version(block) == candidate
                    assert replayed + still_failing == held
                    assert g.quarantine.count(block, QuarantineStatus.QUARANTINED) == still_failing
                s.notes.update(
                    rows_quarantined=held,
                    quarantined_fraction=round(held / r1.decision.total_rows, 4),
                    replayed=replayed,
                    still_failing=still_failing,
                )
            return seconds

        configs.append((s, go))

    measure(configs, repeats, f"recovery {scale:,}")
    floor.notes["what"] = "measured before each timed promotion, same spec and root"
    floor.samples = floor.samples[len(configs) :]  # drop the warm-ups
    return [*series.values(), floor]


# ---------------------------------------------------------------- 4. shadow


def bench_shadow(raw: dict[str, Any], scale: int, repeats: int, blocks: Blocks) -> list[Series]:
    spec = to_spec(scaled(raw, scale))
    block, candidate = blocks.versioned, blocks.candidate
    series = {k: Series("shadow", scale, k, v, "s") for k, v in SHADOW_CONFIGS.items()}

    def go(config: str) -> Callable[[], float]:
        def timed_run() -> float:
            with fresh_root() as root, Guardian(spec, root, sample_rate=SAMPLE_RATE) as g:
                if config == "one":
                    g.shadow_start(block, candidate)
                seconds, report = timed(lambda: run(g, "r1"))
                assert all(r.outcome is Outcome.PASS for r in report.blocks)
                if config == "one":
                    shadow = report.get(block).shadow
                    assert shadow is not None and shadow.version == candidate
                    assert g.active_version(block) != candidate  # one run: never promoted
                    series[config].notes.update(
                        mode=shadow.mode.value, candidate_rows=shadow.rows_in
                    )
            return seconds

        return timed_run

    measure([(series[c], go(c)) for c in series], repeats, f"shadow {scale:,}")
    return list(series.values())


# ---------------------------------------------------------------- derived figures


def derive(series: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Relative figures, from medians: overhead over bare, outage throughput as a share of
    the clean run, and the shadow's added runtime."""
    index = {(s["measurement"], s["scale"], s["config"]): s for s in series if "median" in s}
    out = []

    def add(measurement: str, scale: int, config: str, metric: str, value: float) -> None:
        out.append(dict(measurement=measurement, scale=scale, config=config, metric=metric,
                        value=value))  # fmt: skip

    for (measurement, scale, config), s in index.items():
        if measurement == "overhead" and config != "bare":
            base = index.get((measurement, scale, "bare"))
            if base:
                add(
                    measurement,
                    scale,
                    config,
                    "added_pct",
                    (s["median"] / base["median"] - 1) * 100,
                )
        if measurement == "throughput" and config != "clean":
            base = index.get((measurement, scale, "clean"))
            if base:
                add(measurement, scale, config, "pct_of_clean", s["median"] / base["median"] * 100)
        if measurement == "shadow" and config == "one":
            base = index.get((measurement, scale, "none"))
            if base:
                add(measurement, scale, config, "added_s", s["median"] - base["median"])
                add(
                    measurement,
                    scale,
                    config,
                    "added_pct",
                    (s["median"] / base["median"] - 1) * 100,
                )
    return out


# ---------------------------------------------------------------- environment


def machine() -> dict[str, Any]:
    packages = ["pandas", "pyarrow", "duckdb", "pandera", "numpy", "opentelemetry-sdk"]
    versions = {}
    for p in packages:
        try:
            versions[p] = version(p)
        except PackageNotFoundError:
            versions[p] = "not installed"
    uv = shutil.which("uv")
    uv_version = None
    if uv:
        with contextlib.suppress(OSError, subprocess.SubprocessError):
            uv_version = subprocess.run([uv, "--version"], capture_output=True, text=True).stdout
    return {
        "cpu": cpu_name(),
        "logical_cores": os.cpu_count(),
        "physical_cores": physical_cores(),
        "ram_gib": ram_gib(),
        "os": platform.platform(),
        "python": f"{platform.python_implementation()} {platform.python_version()}",
        "uv": (uv_version or "not found").strip(),
        "packages": versions,
    }


def cpu_name() -> str:
    system = platform.system()
    with contextlib.suppress(Exception):
        if system == "Linux":
            for line in Path("/proc/cpuinfo").read_text().splitlines():
                if line.startswith("model name"):
                    return line.split(":", 1)[1].strip()
        if system == "Windows":
            import winreg

            key = winreg.OpenKey(
                winreg.HKEY_LOCAL_MACHINE, r"HARDWARE\DESCRIPTION\System\CentralProcessor\0"
            )
            return str(winreg.QueryValueEx(key, "ProcessorNameString")[0]).strip()
        if system == "Darwin":
            return subprocess.run(
                ["sysctl", "-n", "machdep.cpu.brand_string"], capture_output=True, text=True
            ).stdout.strip()
    return platform.processor() or platform.machine()


def physical_cores() -> int | None:
    with contextlib.suppress(ImportError):
        import psutil  # optional; not a dependency

        return psutil.cpu_count(logical=False)
    system = platform.system()
    with contextlib.suppress(Exception):
        if system == "Linux":
            cores, current = set(), {}
            for line in [*Path("/proc/cpuinfo").read_text().splitlines(), ""]:
                if ":" in line:
                    k, v = (x.strip() for x in line.split(":", 1))
                    current[k] = v
                elif current:
                    cores.add((current.get("physical id"), current.get("core id")))
                    current = {}
            return len(cores) or None
        if system == "Darwin":
            out = subprocess.run(["sysctl", "-n", "hw.physicalcpu"], capture_output=True, text=True)
            return int(out.stdout)
    return None


def ram_gib() -> float | None:
    system = platform.system()
    with contextlib.suppress(Exception):
        if system == "Linux":
            for line in Path("/proc/meminfo").read_text().splitlines():
                if line.startswith("MemTotal"):
                    return round(int(line.split()[1]) / 1024**2, 1)
        if system == "Windows":
            import ctypes

            class MemoryStatus(ctypes.Structure):
                _fields_ = [
                    ("dwLength", ctypes.c_ulong),
                    ("dwMemoryLoad", ctypes.c_ulong),
                    ("ullTotalPhys", ctypes.c_ulonglong),
                    ("ullAvailPhys", ctypes.c_ulonglong),
                    ("ullTotalPageFile", ctypes.c_ulonglong),
                    ("ullAvailPageFile", ctypes.c_ulonglong),
                    ("ullTotalVirtual", ctypes.c_ulonglong),
                    ("ullAvailVirtual", ctypes.c_ulonglong),
                    ("sullAvailExtendedVirtual", ctypes.c_ulonglong),
                ]

            status = MemoryStatus()
            status.dwLength = ctypes.sizeof(MemoryStatus)
            ctypes.windll.kernel32.GlobalMemoryStatusEx(ctypes.byref(status))  # type: ignore[attr-defined]
            return round(status.ullTotalPhys / 1024**3, 1)
        if system == "Darwin":
            out = subprocess.run(["sysctl", "-n", "hw.memsize"], capture_output=True, text=True)
            return round(int(out.stdout) / 1024**3, 1)
    return None


# ---------------------------------------------------------------- output


def write_results(path: Path, meta: dict[str, Any], blocks: Blocks, series: list[Series]) -> dict:
    summaries = [s.summary() for s in series]
    results = {
        "schema": 1,
        "meta": meta,
        "blocks": blocks.as_dict(),
        "series": summaries,
        "derived": derive(summaries),
    }
    tmp = path.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(results, indent=2) + "\n", encoding="utf-8")
    os.replace(tmp, path)
    return results


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--scales", type=int, nargs="+", help=f"rows (default {SCALES})")
    parser.add_argument("--repeats", type=int, help=f"measured repeats (default {REPEATS})")
    parser.add_argument("--quick", action="store_true", help="10k rows, 2 repeats")
    parser.add_argument(
        "--only", nargs="+", choices=MEASUREMENTS, default=list(MEASUREMENTS), metavar="NAME"
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=BENCH,
        help="where results.json and results.md go (--quick: results-quick.*)",
    )
    args = parser.parse_args(argv)
    scales = tuple(args.scales or (QUICK_SCALES if args.quick else SCALES))
    repeats = args.repeats or (QUICK_REPEATS if args.quick else REPEATS)
    if repeats < 1 or any(s < 100 for s in scales):
        parser.error("--repeats must be >= 1 and every scale >= 100 rows")
    stem = "results-quick" if args.quick else "results"
    args.out_dir.mkdir(parents=True, exist_ok=True)
    json_path, md_path = args.out_dir / f"{stem}.json", args.out_dir / f"{stem}.md"

    raw = raw_spec()
    blocks = pick_blocks(to_spec(raw))
    columns = derived_columns(to_spec(scaled(raw, 2_000, clean=True)), blocks.versioned)
    commit, dirty = git_commit(REPO)
    meta = {
        "command": " ".join(["python", "bench/run_bench.py", *sys.argv[1:]]),
        "quick": args.quick,
        "complete": False,
        "started": datetime.now(UTC).isoformat(timespec="seconds"),
        "finished": None,
        "scales": list(scales),
        "repeats": repeats,
        "warmups": 1,
        "sample_rate": SAMPLE_RATE,
        "quarantine_fractions": list(QUARANTINE_FRACTIONS),
        "measurements": args.only,
        "git_commit": commit,
        "git_dirty": dirty,
        "machine": machine(),
    }
    log(f"blocks by role: {blocks.as_dict()}")
    log(f"scales {list(scales)}, {repeats} repeats, writing {json_path}")

    series: list[Series] = []
    for scale in scales:
        for measurement in args.only:
            log(f"{measurement} at {scale:,} rows")
            if measurement == "overhead":
                series += bench_overhead(raw, scale, repeats)
            elif measurement == "throughput":
                series += bench_throughput(raw, scale, repeats, blocks)
            elif measurement == "recovery":
                series += bench_recovery(raw, scale, repeats, blocks, columns)
            else:
                series += bench_shadow(raw, scale, repeats, blocks)
            write_results(json_path, meta, blocks, series)  # partial results survive a crash

    meta.update(complete=True, finished=datetime.now(UTC).isoformat(timespec="seconds"))
    results = write_results(json_path, meta, blocks, series)
    sys.path.insert(0, str(BENCH))
    from update_readme import render_results_md

    md_path.write_text(render_results_md(results), encoding="utf-8")
    log(f"wrote {json_path} and {md_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
